name: Continuous Integration

on:
  workflow_dispatch:
  workflow_call:
  push:
    branches:
      - master
    paths-ignore:
      - '**/.github/**'
  pull_request:
    branches:
      - master

jobs:
  linux:
    name: Package Linux
    uses: ./.github/workflows/package-linux.yml

  windows:
    name: Package Windows
    uses: ./.github/workflows/package-windows.yml

  macos:
    name: Package MacOS
    uses: ./.github/workflows/package-macos.yml

  check_all_jobs:
    name: Check All Jobs
    runs-on: ubuntu-latest
    needs: [linux, windows, macos]
    steps:
      - name: Check Job Status
        id: job-status
        run: echo "All previous jobs succeeded"

  trigger_release:
    name: Trigger Release
    needs: check_all_jobs
    runs-on: ubuntu-latest
    if: ${{ needs.check_all_jobs.result == 'success' }}
    steps:
      - name: Trigger release.yml workflow
        uses: actions/github-script@v5
        with:
          script: |
            const response = await octokit.actions.createWorkflowDispatch({
              owner: context.repo.owner,
              repo: context.repo.repo,
              workflow_file: 'release.yml'
            });
            console.log(response);
