name: Package - Linux
on:
  workflow_dispatch:
  workflow_call:

jobs:
  package:
    name: GCC 12
    runs-on: ubuntu-22.04
    steps:
      - name: Clone Repository
        uses: actions/checkout@v4

      - name: Install Dependencies
        run: >
          sudo apt-get update

          sudo apt install -y
          gcc-12 g++-12
          python3
          scons
          libsdl1.2-dev
          libsdl-image1.2-dev
          libsdl-mixer1.2-dev
          libphysfs-dev
          libpng-dev

      - name: Collect architecture
        id: architecture
        run: |
          printf 'uname_m=%s\n' "$(uname -m)" >> "$GITHUB_OUTPUT"

      - name: Configure and Build
        run: scons -j`nproc`
        env:
          CXX: g++-12

      - name: Install AppImage Requirements
        run: sudo apt-get install -y libfuse2 wget curl

      - name: Package
        run: ./contrib/packaging/linux/build_package.sh
        env:
          rebirth_uname_m: ${{ steps.architecture.outputs.uname_m }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: "DXX-Rebirth-Linux-AppImage-${{ steps.architecture.outputs.uname_m }}"
          path: 'D*X-Rebirth.AppImage'
