name: Package All and Create Release
on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: Tag Name (new or existing)
        required: true
        type: string
      prerelease:
        description: Pre-release?
        default: true
        type: boolean
  push:
    tags:
      - "v*.*"

jobs:
  package:
    name: Package All
    uses: ./.github/workflows/ci.yml

  release:
    name: Create Release
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    needs:
      - package
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Display Artifacts
        run: ls -R
        
      - name: Create ZIP files
        run: |
          cd ./DXX-Rebirth-Debian-Bookworm && zip -r ../dxx-rebirth-linux-arm64.zip ./*
          cd ../DXX-Rebirth-Linux-AppImage-x86_64 && zip -r ../dxx-rebirth-linux-x86_64.zip ./*
          cd ../DXX-Rebirth-MacOS14-arm64 && zip -r ../dxx-rebirth-macos-arm64.zip ./*
          cd ../DXX-Rebirth-Windows-x86_64 && zip -r ../dxx-rebirth-windows-x64.zip ./*

      - name: Compress Artifacts
        run: for dir in */; do (cd "$dir" && zip -r "../${dir%/}.zip" .); done

      - name: Create Release
        uses: softprops/action-gh-release@9d7c94cfd0a1f3ed45544c887983e9fa900f0564
        with:
          tag_name: ${{ inputs.tag_name || github.ref_name }}
          prerelease: ${{ inputs.prerelease || contains(github.ref_name, '-') }}
          generate_release_notes: true
          files: '*.zip'
